# Generated by Django 3.0.7 on 2021-06-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='datecompleted',
        ),
    ]
